<?php

/**
 * @file
 * Contains ewp_ounits.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;

/**
 * Implements hook_help().
 */
function ewp_ounits_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ewp_ounits module.
    case 'help.page.ewp_ounits':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal implementation of the EWP Organizational Units API') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ewp_ounits_theme($existing, $type, $theme, $path) {
  return [
    'ounit' => [
      'path' => $path . '/templates',
      'template'  => 'ounit',
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function ewp_ounits_theme_suggestions_ounit(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#ounit'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'ounit__' . $sanitized_view_mode;
  $suggestions[] = 'ounit__' . $entity->id();
  $suggestions[] = 'ounit__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Prepares variables for Organizational Unit templates.
 *
 * Default template: ounit.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_ounit(array &$variables) {
  // Helpful $content variable for templates.
  $variables['content'] = [];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  /** @var OunitInterface $entity */
  $entity = $variables['elements']['#ounit'];
  // provide the label
  $variables['label'] = $entity->label();
  // provide the alias
  $variables['url'] = $entity->toUrl()->toString();
  // provide the view mode
  $variables['view_mode'] = $variables['elements']['#view_mode'];
}

/**
 * Implements hook_jsonapi_entity_filter_access() for 'ounit'.
 */
function ewp_ounits_jsonapi_entity_filter_access(EntityTypeInterface $entity_type, AccountInterface $account) {
  return ([
    JSONAPI_FILTER_AMONG_ALL => AccessResult::allowed(),
  ]);
}

/**
 * Implements hook_jsonapi_ENTITY_TYPE_filter_access() for 'ounit'.
 */
function ewp_ounits_jsonapi_ounit_filter_access(EntityTypeInterface $entity_type, AccountInterface $account) {
  return ([
    JSONAPI_FILTER_AMONG_ALL => AccessResult::allowedIfHasPermission($account, 'view unpublished organizational unit entities'),
    JSONAPI_FILTER_AMONG_PUBLISHED => AccessResult::allowedIfHasPermission($account, 'view published organizational unit entities'),
    JSONAPI_FILTER_AMONG_OWN => AccessResult::allowedIfHasPermission($account, 'view published organizational unit entities'),
  ]);
}
